services:
  stores-api:
    container_name: StoreExplorer-backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "5271:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
